# Manipulation de tableau

In [1]:
import numpy as np

In [3]:
A = np.zeros((3, 2))
B = np.ones((3, 2))

In [5]:
print(A)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [6]:
print(B)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [9]:
C = np.hstack((A, B))
print(C)

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]


In [20]:
D = np.vstack((A, B))
print(D)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [13]:
D.shape

(6, 2)

In [15]:
E = np.concatenate((A, B), 0) # equivalent à vstack
E

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
F = np.concatenate((A, B), 1) # equivalent a hstack
F

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [22]:
D

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
G = D.reshape((3, 4)) # reshape a besoin du meme nombre d elements voir D.size
G

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
H = np.array([1, 2, 3, 4, 5, 6])
H.shape

(6,)

In [24]:
I = H.reshape(H.shape[0], 1)
I.shape

(6, 1)

In [26]:
E

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [27]:
E.ravel()

array([0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 1., 1.])