# INITIALISATION

In [2]:
import numpy as np

# ndarray

In [7]:
array_1 = [1, 2, 3, 4, 5, 6, 7, 9 ]
A = np.array(array_1)
A

array([1, 2, 3, 4, 5, 6, 7, 9])

In [9]:
A.ndim # nombre de dimensions

1

In [11]:
A.shape 

(8,)

In [13]:
A.size

8

In [15]:
B = np.zeros((3, 2)) #zeros prend en argument un tuple 
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [17]:
C = np.ones((3, 4))
C

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
D = np.eye(5) # Interger
D

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
E = np.full((5, 5), 3) # Remplie le shape (5, 5) de chiffre 3
E

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [26]:
np.random.randn(3, 4) # Ne prends pas de tuple prend des nombres aleatoire sur la NORMALE centre sur 0

array([[ 0.76103773,  0.12167502,  0.44386323,  0.33367433],
       [ 1.49407907, -0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 , -0.74216502]])

In [29]:
np.random.seed(0)     #fixe le resultat de randn avec le seed 0
np.random.randn(3, 4)

array([[ 1.76405235,  0.40015721,  0.97873798,  2.2408932 ],
       [ 1.86755799, -0.97727788,  0.95008842, -0.15135721],
       [-0.10321885,  0.4105985 ,  0.14404357,  1.45427351]])

In [32]:
np.linspace(0, 10, 15)  # tableau a une dimension allant de 0 10 avec 15 elements

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [37]:
np.arange(0, 10, 0.5) # Debut Fin Pas

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [41]:
np.linspace(0, 10, 15, dtype=np.float16 ) # de type float 16

array([ 0.    ,  0.7144,  1.429 ,  2.143 ,  2.857 ,  3.572 ,  4.285 ,
        5.    ,  5.715 ,  6.43  ,  7.145 ,  7.855 ,  8.57  ,  9.29  ,
       10.    ], dtype=float16)