In [1]:
import numpy as np

# Indexing

In [2]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
A[0, 0]

1

In [4]:
A[0, 1]

2

In [5]:
A[1, 2]

6

In [6]:
A[:, 0]

array([1, 4, 7])

In [7]:
A[0, :]

array([1, 2, 3])

In [8]:
A[0]

array([1, 2, 3])

In [9]:
A[0:2, 0:2]

array([[1, 2],
       [4, 5]])

In [10]:
B = A[0:2, 0:2]
B.shape

(2, 2)

In [11]:
A[0:2, 0:2] = 10
A

array([[10, 10,  3],
       [10, 10,  6],
       [ 7,  8,  9]])

In [12]:
A[:, -2:]

array([[10,  3],
       [10,  6],
       [ 8,  9]])

In [13]:
C = np.zeros((4, 4))
C

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
C[1:3, 1:3] = 1
C

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

In [15]:
D = np.zeros((5, 5))
D

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
D[::2, ::2] = 1 # Toutes les lignes avec un pas de 2 toutes les colonnes avec un pas de 2
D

array([[1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 0., 1., 0., 1.]])

# Boolean Indexing

In [17]:
E = np.random.randint(0, 10, [5, 5])
E

array([[2, 2, 5, 7, 2],
       [7, 4, 5, 3, 2],
       [6, 7, 5, 2, 8],
       [0, 5, 8, 5, 9],
       [8, 5, 2, 8, 3]])

In [18]:
E < 5

array([[ True,  True, False, False,  True],
       [False,  True, False,  True,  True],
       [False, False, False,  True, False],
       [ True, False, False, False, False],
       [False, False,  True, False,  True]])

In [19]:
E[E<5] = 0 # remplace par zero les nombres grace au mask E<5
E

array([[0, 0, 5, 7, 0],
       [7, 0, 5, 0, 0],
       [6, 7, 5, 0, 8],
       [0, 5, 8, 5, 9],
       [8, 5, 0, 8, 0]])

In [20]:
F = np.random.randint(0, 10, [5, 5])
print(F)
F[(F<5) & (F>2)] = 10
F

[[3 2 7 0 8]
 [3 7 1 3 7]
 [2 6 6 2 3]
 [2 6 6 4 7]
 [6 6 6 4 8]]


array([[10,  2,  7,  0,  8],
       [10,  7,  1, 10,  7],
       [ 2,  6,  6,  2, 10],
       [ 2,  6,  6, 10,  7],
       [ 6,  6,  6, 10,  8]])

In [22]:
G = np.random.randint(0, 10, [5, 5])
print(G)
G[G<5] # Detruit la forme du tableau

[[1 5 3 6 6]
 [7 7 5 9 6]
 [9 8 6 5 2]
 [1 3 8 0 5]
 [7 5 3 7 7]]


array([1, 3, 2, 1, 3, 0, 3])

In [30]:
H = np.random.randint(10, size=(5, 5))
H[G<5]  # Affiche H mais filtré par G<5

array([8, 3, 1, 3, 6, 5, 8])